fix: should resume in_progress builds
this PR contains fixes for the update-fbc-catalog task

- fixes the case where resume does not happen for in_progress IIB
  builds and adds tests for the case;
- removes shellcheck disables and fix errors;

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

diff --git a/tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml b/tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml
--- a/tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml
+++ b/tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml
@@ -55,23 +55,39 @@ spec:
         steps:
           - name: check-result
             image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
+            env:
+              - name: BUILD_STATE
+                value: $(params.buildState)
+              - name: GENERIC_RESULT
+                value: $(params.genericResult)
+              - name: JSON_BUILDINFO
+                value: $(params.jsonBuildInfo)
             script: |
               #!/bin/bash
               set -x
 
               # the jsonBuild mockes has 10 keys on it
-              keyLength=$(jq '. | length' <<< '$(params.jsonBuildInfo)')
+              keyLength=$(jq '. | length' <<< "${JSON_BUILDINFO}")
               if [ "$keyLength" -ne 10 ]; then
                 echo "The task did not save a valid json in jsonBuildInfo result"
                 exit 1
               fi
 
-              # shellcheck disable=SC2046 # (warning): Quote this to prevent word splitting
-              # reason: wrapping the tekton parameters in the following line with double quotes is adding unwanted
-              #         quotes to the contained json, breaking jq.
-              state="$(jq -cr '.state' <<< $(params.buildState))"
+              # jq fails to extract the required keys from a escaped json, so the json is first evaluated and then
+              # the keys contents are extracted.
+              state="$(jq -cr <<< "${BUILD_STATE}" | jq -r .state)"
               if [ "$state" != "complete" ]; then
                 echo "The task did not save a completed IIB build in buildState result"
+                exit 1
+              fi
+
+              # jq fails to extract the required keys from a escaped json, so the json is first evaluated and then
+              # the keys contents are extracted.
+              genericResult=$(jq -cr <<< "${GENERIC_RESULT}" | jq -r \
+                '. |[.fbc_opt_in, .overwrite_fromindex_image, .publish_index_image,.sign_index_image] |@csv')
+
+              if [ "$genericResult" != '"true","false","true","true"' ]; then
+                echo "The stask did not save the correct values in genericResult result"
                 exit 1
               fi
 
@@ -83,17 +99,6 @@ spec:
               iibLog=$(awk '{match($0, /https.*/); print(substr($0, RSTART)) }' <<< "$(params.iibLog)")
               if [  "$iibLog" != "https://fakeiib.host/api/v1/builds/1/logs" ]; then
                 echo "The task did not save a valid iib log url in the iibLog result"
-                exit 1
-              fi
-
-              # shellcheck disable=SC2046 # (warning): Quote this to prevent word splitting
-              # reason: wrapping the tekton parameters in the following line with double quotes is adding unwanted
-              #         quotes to the contained json, breaking jq.
-              genericResult=$(jq -r \
-                '. |[.fbc_opt_in, .overwrite_fromindex_image, .publish_index_image, .sign_index_image] |@csv' \
-                <<< $(params.genericResult))
-              if [ "$genericResult" != '"true","false","true","true"' ]; then
-                echo "The stask did not save the correct values in genericResult result"
                 exit 1
               fi
 
