fix(CLOUDDST-24922): retry cosign in signing task (#683)
Retry failed cosign so that signing doesn't fail with temporary issues
on pushing to quay.io.

Signed-off-by: Emily Zheng <yuzheng@redhat.com>

diff --git a/tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml b/tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
--- a/tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
+++ b/tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: rh-sign-image-cosign
   labels:
-    app.kubernetes.io/version: "1.1.0"
+    app.kubernetes.io/version: "1.2.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -24,6 +24,10 @@ spec:
         The relative path in the workspace to a text file that contains a list of repositories
         that needs registry.access.redhat.com image references to be signed (i.e.
         requires_terms=true), one repository string per line, e.g. "rhtas/cosign-rhel9".
+    - name: retries
+      description: Retry cosign N times.
+      type: string
+      default: "3"
   workspaces:
     - name: data
       description: Workspace to read and save files
@@ -70,6 +74,28 @@ spec:
             exit 1
         fi
 
+        run_cosign () { # Expected arguments are [digest_reference, tag_reference]
+            # Upload transparency log when rekor url is specified
+            if [ -v REKOR_URL ]; then
+                COSIGN_COMMON_ARGS="-y --rekor-url=$REKOR_URL --key $SIGN_KEY"
+            else
+                COSIGN_COMMON_ARGS="--tlog-upload=false --key $SIGN_KEY"
+            fi
+            echo "Signing manifest $1 ($2)"
+            attempt=0
+            until [ "$attempt" -gt "$(params.retries)" ] ; do # 3 retries by default
+                cosign -t 3m0s sign\
+                ${COSIGN_COMMON_ARGS}\
+                --sign-container-identity "$2"\
+                "$1" && break
+                attempt=$((attempt+1))
+            done
+            if [ "$attempt" -gt "$(params.retries)" ] ; then
+              echo "Max retries exceeded."
+              exit 1
+            fi
+        }
+
         for (( COMPONENTS_INDEX=0; COMPONENTS_INDEX<COMPONENTS_LENGTH; COMPONENTS_INDEX++ )); do
             COMPONENT_NAME=$(jq -r ".components[${COMPONENTS_INDEX}].name" "${SNAPSHOT_PATH}")
             echo "Processing component ${COMPONENT_NAME}"
@@ -98,23 +124,12 @@ spec:
             if [ "$MEDIA_TYPE" = "application/vnd.docker.distribution.manifest.list.v2+json" ]; then LIST=1; fi
             if [ "$MEDIA_TYPE" = "application/vnd.oci.image.index.v1+json" ]; then LIST=1; fi
 
-            # Upload transparency log when rekor url is specified
-            if [ -v REKOR_URL ]; then
-                COSIGN_COMMON_ARGS="-y --rekor-url=$REKOR_URL --key $SIGN_KEY"
-            else
-                COSIGN_COMMON_ARGS="--tlog-upload=false --key $SIGN_KEY"
-            fi
-
             # Sign each manifest in manifest list
             if [ $LIST -eq 1 ]; then
                 for REGISTRY_REF in "${REGISTRY_REFERENCES[@]}"; do
                     for MDIGEST in $(echo "$IMAGE" | jq -r '.manifests[]|.digest'); do
                         for TAG in $TAGS; do
-                            echo "Signing manifest ${INTERNAL_CONTAINER_REF}:${TAG} (${MDIGEST})"
-                            cosign -t 3m0s sign\
-                            ${COSIGN_COMMON_ARGS}\
-                            --sign-container-identity "${REGISTRY_REF}:${TAG}"\
-                            "${INTERNAL_CONTAINER_REF}@${MDIGEST}"
+                            run_cosign "${INTERNAL_CONTAINER_REF}@${MDIGEST}" "${REGISTRY_REF}:${TAG}"
                         done
                     done
                 done
@@ -123,11 +138,7 @@ spec:
             # Sign manifest list itself or manifest if it's not list
             for REGISTRY_REF in "${REGISTRY_REFERENCES[@]}"; do
                 for TAG in $TAGS; do
-                    echo "Signing manifest ${INTERNAL_CONTAINER_REF}:${TAG} (${DIGEST})"
-                    cosign -t 3m0s sign\
-                    ${COSIGN_COMMON_ARGS}\
-                    --sign-container-identity "${REGISTRY_REF}:${TAG}"\
-                    "${INTERNAL_CONTAINER_REF}@${DIGEST}"
+                    run_cosign "${INTERNAL_CONTAINER_REF}@${DIGEST}" "${REGISTRY_REF}:${TAG}"
                 done
             done
         done
