fix: strip .git suffix from repo url in check-data-keys (#759)
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/check-data-keys/check-data-keys.yaml b/tasks/check-data-keys/check-data-keys.yaml
--- a/tasks/check-data-keys/check-data-keys.yaml
+++ b/tasks/check-data-keys/check-data-keys.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: check-data-keys
   labels:
-    app.kubernetes.io/version: "1.0.1"
+    app.kubernetes.io/version: "1.0.2"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -31,6 +31,9 @@ spec:
     - name: check-data-keys
       image: quay.io/konflux-ci/release-service-utils:9089cafbf36bb889b4b73d8c2965613810f13736
       args: ["$(params.systems[*])"]
+      env:
+        - name: "SCHEMA_FILE"
+          value: "$(params.schema)"
       script: |
         #!/usr/bin/env bash
         set -ex
@@ -40,8 +43,9 @@ spec:
             exit 1
         fi
 
-        if ! curl -sL --fail-with-body "$(params.schema)" -o /tmp/schema ; then
-            echo "Failed to download schema file: $(params.schema)"
+        schema="${SCHEMA_FILE/\.git\///}"
+        if ! curl -sL --fail-with-body "$schema" -o /tmp/schema ; then
+            echo "Failed to download schema file: $schema"
             exit 1
         fi
 
